spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/user/**
#        - id: user-client-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/client/**
        - id: user-service-eureka-emin
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: user-client-service-eureka
          uri: lb://user-service-client
          predicates:
            - Path=/client/**
          filters:
            - AuthFilter

        - id: auth-service-eureka
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true